"""
create_behavioral_notebook.py
生成 01_behavioral_finance.ipynb
並將現有 01–10 推後一位變成 02–11
"""

import json, uuid, pathlib, shutil

BASE = pathlib.Path('/Users/tsaichengyu/Documents/Projects/Academic/學術研究_教材')

def cid(): return uuid.uuid4().hex[:8]
def md(source): return {"cell_type":"markdown","id":cid(),"metadata":{},"source":source}
def code(source): return {"cell_type":"code","id":cid(),"execution_count":None,"metadata":{},"outputs":[],"source":source}
def nb(cells):
    return {"nbformat":4,"nbformat_minor":5,
            "metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},
                        "language_info":{"name":"python","version":"3.9.0"}},
            "cells":cells}

# ──────────────────────────────────────────────────────────────────────────────
# 先把 01–10 推後一位（10→11, 9→10, ...）
# ──────────────────────────────────────────────────────────────────────────────

RENAMES = [
    ('10_momentum.ipynb',       '11_momentum.ipynb'),
    ('09_ff5_quality.ipynb',    '10_ff5_quality.ipynb'),
    ('08_fama_french.ipynb',    '09_fama_french.ipynb'),
    ('07_factor_zoo.ipynb',     '08_factor_zoo.ipynb'),
    ('06_january_effect.ipynb', '07_january_effect.ipynb'),
    ('05_dca_vs_lumpsum.ipynb', '06_dca_vs_lumpsum.ipynb'),
    ('04_trinity_study.ipynb',  '05_trinity_study.ipynb'),
    ('03_capm_reality.ipynb',   '04_capm_reality.ipynb'),
    ('02_damodaran.ipynb',      '03_damodaran.ipynb'),
    ('01_shiller_cape.ipynb',   '02_shiller_cape.ipynb'),
]

print('重新編號現有 notebooks…')
for old, new in RENAMES:
    p = BASE / old
    if p.exists():
        p.rename(BASE / new)
        print(f'  {old} → {new}')

# ──────────────────────────────────────────────────────────────────────────────
# 行為金融 Notebook
# ──────────────────────────────────────────────────────────────────────────────

cells = [

md(["# 01｜行為金融學：散戶為什麼一直虧錢？\n",
    "\n",
    "**核心論文：**\n",
    "- Kahneman & Tversky (1979), *Prospect Theory*, Econometrica\n",
    "- Odean (1998), *Are Investors Reluctant to Realize Their Losses?*, Journal of Finance\n",
    "- Barber & Oden (2000), *Trading is Hazardous to Your Wealth*, Journal of Finance\n",
    "- Baker & Wurgler (2006), *Investor Sentiment and the Cross-Section of Stock Returns*, Journal of Finance\n",
    "\n",
    "在學術研究的每一個「市場異象」背後，都有一個共同的元兇：**人類的非理性行為**。\n",
    "本章不談「應該怎麼做」，而是先正視「人類天生就會犯哪些錯」。"]),

md(["## 🎯 學習目標\n",
    "1. 理解展望理論如何描述人類對「獲利」與「虧損」的不對稱感受\n",
    "2. 認識五個最常見的散戶認知偏誤及其學術依據\n",
    "3. 用數據看懂「阿媽理論」——情緒頂點往往是市場頂點"]),

code(["import numpy as np\n",
      "import pandas as pd\n",
      "import matplotlib\n",
      "matplotlib.rcParams['font.family'] = [\n",
      "    'Microsoft YaHei', 'SimHei', 'Heiti TC',\n",
      "    'PingFang HK', 'STHeiti', 'Arial Unicode MS', 'sans-serif'\n",
      "]\n",
      "matplotlib.rcParams['axes.unicode_minus'] = False\n",
      "import matplotlib.pyplot as plt\n",
      "import matplotlib.patches as mpatches\n",
      "from scipy import stats\n",
      "import warnings, pathlib\n",
      "warnings.filterwarnings('ignore')\n",
      "\n",
      "DATA_DIR = pathlib.Path('data')\n",
      "DATA_DIR.mkdir(exist_ok=True)\n",
      "print('環境就緒')"]),

# ── Section 1: Prospect Theory ────────────────────────────────────────────────

md(["## 1｜展望理論：損失比獲利更痛\n",
    "\n",
    "**傳統經濟學假設：** 人是理性的，1萬元的損失和1萬元的獲利帶來同等強度的感受（只是方向相反）。\n",
    "\n",
    "**Kahneman & Tversky（1979）的發現：** 完全不是。\n",
    "\n",
    "> **損失的痛苦 ≈ 獲利喜悅的 2.25 倍**\n",
    "\n",
    "這個叫做**損失厭惡（Loss Aversion）**。它解釋了很多投資人的奇怪行為：\n",
    "- 明明股票已經跌了50%，就是不肯停損\n",
    "- 賺了10%馬上想出場，卻對-10%視而不見\n",
    "- 寧願選「確定獲利5%」而非「50%機率獲利11%」"]),

code(["# 展望理論的價值函數 vs 傳統效用函數\n",
      "x = np.linspace(-200, 200, 1000)\n",
      "\n",
      "def prospect_value(x, alpha=0.88, beta=0.88, lambda_=2.25):\n",
      "    \"\"\"Tversky & Kahneman (1992) 的價值函數參數\"\"\"\n",
      "    v = np.where(x >= 0,\n",
      "                  x ** alpha,\n",
      "                 -lambda_ * ((-x) ** beta))\n",
      "    return v\n",
      "\n",
      "def linear_utility(x):\n",
      "    return x\n",
      "\n",
      "pv = prospect_value(x)\n",
      "lu = linear_utility(x)\n",
      "\n",
      "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
      "\n",
      "# 左圖：完整價值函數\n",
      "ax = axes[0]\n",
      "ax.plot(x, pv, color='#E91E63', linewidth=2.5, label='展望理論價值函數')\n",
      "ax.plot(x, lu * 0.8, color='#9E9E9E', linewidth=1.5, linestyle='--', label='傳統效用（理性人）')\n",
      "ax.axhline(0, color='black', linewidth=0.8)\n",
      "ax.axvline(0, color='black', linewidth=0.8)\n",
      "\n",
      "# 標注不對稱\n",
      "gain_100 = prospect_value(np.array([100.0]))[0]\n",
      "loss_100 = prospect_value(np.array([-100.0]))[0]\n",
      "ax.annotate(f'+100的喜悅\\n={gain_100:.1f}', xy=(100, gain_100),\n",
      "            xytext=(30, gain_100+30), fontsize=9,\n",
      "            arrowprops=dict(arrowstyle='->', color='green'), color='green')\n",
      "ax.annotate(f'-100的痛苦\\n={loss_100:.1f}', xy=(-100, loss_100),\n",
      "            xytext=(-170, loss_100+30), fontsize=9,\n",
      "            arrowprops=dict(arrowstyle='->', color='red'), color='red')\n",
      "ax.set_xlabel('損益金額', fontsize=11)\n",
      "ax.set_ylabel('心理感受強度', fontsize=11)\n",
      "ax.set_title('展望理論：損失的痛苦遠大於獲利的喜悅', fontsize=12, fontweight='bold')\n",
      "ax.legend(fontsize=10)\n",
      "ax.grid(alpha=0.3)\n",
      "\n",
      "# 右圖：確定獲利 vs 賭博的選擇\n",
      "ax2 = axes[1]\n",
      "scenarios = {\n",
      "    '確定獲利\\n$5,000': 5000**0.88,\n",
      "    '50%機率獲利\\n$11,000': 0.5 * (11000**0.88),\n",
      "    '確定虧損\\n-$5,000': -2.25*(5000**0.88),\n",
      "    '50%機率虧損\\n-$11,000': 0.5 * (-2.25*(11000**0.88)),\n",
      "}\n",
      "colors_bar = ['#4CAF50','#8BC34A','#F44336','#FF7043']\n",
      "bars = ax2.bar(list(scenarios.keys()), list(scenarios.values()),\n",
      "               color=colors_bar, alpha=0.85, edgecolor='white')\n",
      "ax2.axhline(0, color='black', linewidth=0.8)\n",
      "ax2.set_title('理性人選賭博，但多數人選確定獲利\\n（損失時反而選賭博，因為損失痛苦太大）',\n",
      "              fontsize=11, fontweight='bold')\n",
      "ax2.set_ylabel('展望理論主觀價值')\n",
      "ax2.grid(alpha=0.3, axis='y')\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/prospect_theory.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "print(f'損失厭惡係數 λ = 2.25')\n",
      "print(f'+100 的喜悅：{gain_100:.1f}')\n",
      "print(f'-100 的痛苦：{loss_100:.1f}')\n",
      "print(f'痛苦/喜悅 比值：{abs(loss_100/gain_100):.2f}x')"]),

# ── Section 2: Disposition Effect ─────────────────────────────────────────────

md(["## 2｜處置效應：賣贏留輸（散戶最常見的錯誤）\n",
    "\n",
    "**Odean（1998）** 分析了10,000個散戶券商帳戶：\n",
    "\n",
    "> 散戶賣出「賺錢股票」的機率，是賣出「虧錢股票」的 **1.5 倍**。\n",
    "\n",
    "這叫 **處置效應（Disposition Effect）**：\n",
    "- 🟢 賺錢 → 馬上賣，鎖住獲利（因為展望理論：確定獲利 > 繼續賭）\n",
    "- 🔴 虧錢 → 死抱不賣，等「回本」（因為展望理論：確定虧損太痛，寧願賭一把）\n",
    "\n",
    "**諷刺的是：** 動能研究告訴我們，強勢股往往繼續漲，弱勢股往往繼續跌。\n",
    "散戶的處置效應剛好反著做。"]),

code(["# 模擬：有處置效應的散戶 vs 無偏誤的投資人\n",
      "np.random.seed(42)\n",
      "N_STOCKS = 500\n",
      "N_MONTHS = 12\n",
      "\n",
      "# 模擬500支股票的12個月報酬（帶動能：強者繼續強）\n",
      "first_month  = np.random.normal(0.01, 0.08, N_STOCKS)\n",
      "# 動能：後11個月報酬與第一個月正相關\n",
      "future_returns = np.array([\n",
      "    first_month * 0.3 + np.random.normal(0.008, 0.07, N_STOCKS)\n",
      "    for _ in range(N_MONTHS)\n",
      "])\n",
      "\n",
      "winners = first_month > 0   # 第一個月賺錢的股票\n",
      "losers  = first_month <= 0  # 第一個月虧錢的股票\n",
      "\n",
      "# 有處置效應：賣贏（錯過後續上漲），留輸（繼續承受下跌）\n",
      "# 沒有偏誤：持有所有股票\n",
      "future_cum = (1 + future_returns).prod(axis=0) - 1\n",
      "\n",
      "winner_future = future_cum[winners]\n",
      "loser_future  = future_cum[losers]\n",
      "\n",
      "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
      "\n",
      "# 左圖：賣掉贏家後，那些贏家繼續漲了多少？\n",
      "ax = axes[0]\n",
      "ax.hist(winner_future * 100, bins=30, color='#4CAF50', alpha=0.7, label=f'贏家後續報酬\\n(平均={winner_future.mean()*100:.1f}%)')\n",
      "ax.hist(loser_future * 100,  bins=30, color='#F44336', alpha=0.7, label=f'輸家後續報酬\\n(平均={loser_future.mean()*100:.1f}%)')\n",
      "ax.axvline(winner_future.mean()*100, color='#2E7D32', linewidth=2, linestyle='--')\n",
      "ax.axvline(loser_future.mean()*100,  color='#B71C1C', linewidth=2, linestyle='--')\n",
      "ax.axvline(0, color='black', linewidth=0.8)\n",
      "ax.set_xlabel('後續12個月報酬 (%)')\n",
      "ax.set_ylabel('股票數量')\n",
      "ax.set_title('你賣掉的贏家繼續漲\\n你留著的輸家繼續跌', fontsize=12, fontweight='bold')\n",
      "ax.legend(fontsize=10)\n",
      "ax.grid(alpha=0.3)\n",
      "\n",
      "# 右圖：處置效應投資人 vs 持有不動\n",
      "ax2 = axes[1]\n",
      "# 處置效應投資人：賣掉贏家（持有現金）、留住輸家\n",
      "disposition_portfolio = loser_future.mean()  # 只剩輸家\n",
      "hold_portfolio = future_cum.mean()            # 持有全部\n",
      "sell_winners   = winner_future.mean()         # 賣掉後現金（假設0）\n",
      "\n",
      "labels = ['持有全部\\n（無偏誤）', '賣贏留輸\\n（處置效應）', '只持有贏家\\n（反向操作）']\n",
      "values = [hold_portfolio*100, disposition_portfolio*100, winner_future.mean()*100]\n",
      "colors_b = ['#2196F3', '#F44336', '#4CAF50']\n",
      "bars = ax2.bar(labels, values, color=colors_b, alpha=0.85, edgecolor='white')\n",
      "ax2.axhline(0, color='black', linewidth=0.8)\n",
      "for bar, v in zip(bars, values):\n",
      "    ax2.text(bar.get_x()+bar.get_width()/2, v+(0.3 if v>=0 else -0.8),\n",
      "             f'{v:.1f}%', ha='center', fontsize=11, fontweight='bold')\n",
      "ax2.set_ylabel('後續12個月平均報酬 (%)')\n",
      "ax2.set_title('處置效應讓散戶系統性落後', fontsize=12, fontweight='bold')\n",
      "ax2.grid(alpha=0.3, axis='y')\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/disposition_effect.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "print(f'模擬結果（帶動能市場）：')\n",
      "print(f'  持有全部  → {hold_portfolio*100:.1f}%')\n",
      "print(f'  賣贏留輸 → {disposition_portfolio*100:.1f}%')\n",
      "print(f'  差距：{(hold_portfolio - disposition_portfolio)*100:.1f} 個百分點/年')"]),

# ── Section 3: Overconfidence ─────────────────────────────────────────────────

md(["## 3｜過度自信：每個人都覺得自己比平均好\n",
    "\n",
    "**Barber & Odean（2000）** 分析 66,465 個散戶帳戶（1991–1997）：\n",
    "\n",
    "| 族群 | 年換手率 | 年化報酬 | 市場報酬 | **超額報酬** |\n",
    "|------|----------|----------|----------|-------------|\n",
    "| 最低交易頻率（Q1） | 19% | 18.5% | 17.1% | **+1.4%** |\n",
    "| 最高交易頻率（Q5） | 258% | 11.4% | 17.1% | **−5.7%** |\n",
    "| 男性平均 | 77% | 2.65% 落後 | — | — |\n",
    "| 女性平均 | 53% | 1.72% 落後 | — | — |\n",
    "\n",
    "**結論：** 交易越頻繁，虧越多。男性因為更過度自信，交易更頻繁，輸更多。\n",
    "\n",
    "研究的核心公式：\n",
    "$$\\text{淨報酬} = \\text{毛報酬} - \\text{交易成本} - \\text{選股劣勢}$$"]),

code(["# 複製 Barber & Odean (2000) 的核心發現\n",
      "# 交易成本對長期報酬的侵蝕\n",
      "\n",
      "years = 20\n",
      "market_return = 0.10   # 年化10%\n",
      "initial = 1_000_000   # 100萬\n",
      "\n",
      "# 不同頻率的交易者（換手率 × 成本）\n",
      "traders = {\n",
      "    '懶人投資者\\n(換手率5%)':   {'turnover': 0.05, 'cost_per_turn': 0.005, 'selection': 0.0},\n",
      "    '普通散戶\\n(換手率80%)':   {'turnover': 0.80, 'cost_per_turn': 0.005, 'selection': -0.01},\n",
      "    '積極交易者\\n(換手率250%)': {'turnover': 2.50, 'cost_per_turn': 0.005, 'selection': -0.02},\n",
      "    '當沖達人\\n(換手率800%)':  {'turnover': 8.00, 'cost_per_turn': 0.003, 'selection': -0.03},\n",
      "}\n",
      "\n",
      "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
      "\n",
      "final_values = {}\n",
      "colors_t = ['#4CAF50', '#2196F3', '#FF9800', '#F44336']\n",
      "\n",
      "for (name, params), color in zip(traders.items(), colors_t):\n",
      "    annual_cost = params['turnover'] * params['cost_per_turn']\n",
      "    net_return  = market_return + params['selection'] - annual_cost\n",
      "    values = [initial * (1 + net_return)**t for t in range(years+1)]\n",
      "    axes[0].plot(range(years+1), [v/1e6 for v in values],\n",
      "                 label=f'{name}\\n淨報酬={net_return*100:.1f}%',\n",
      "                 color=color, linewidth=2)\n",
      "    final_values[name] = values[-1]\n",
      "\n",
      "axes[0].set_xlabel('年份')\n",
      "axes[0].set_ylabel('資產（百萬元）')\n",
      "axes[0].set_title(f'20年後：交易越頻繁，差距越大\\n（初始資金 100萬）', fontsize=12, fontweight='bold')\n",
      "axes[0].legend(fontsize=8, loc='upper left')\n",
      "axes[0].grid(alpha=0.3)\n",
      "\n",
      "# 右圖：20年後的財富差異\n",
      "names = list(final_values.keys())\n",
      "vals  = [v/1e6 for v in final_values.values()]\n",
      "bars = axes[1].bar(names, vals, color=colors_t, alpha=0.85, edgecolor='white')\n",
      "for bar, v in zip(bars, vals):\n",
      "    axes[1].text(bar.get_x()+bar.get_width()/2, v+0.05, f'{v:.2f}M', ha='center', fontsize=10)\n",
      "axes[1].set_ylabel('20年後資產（百萬）')\n",
      "axes[1].set_title('20年後的財富差距', fontsize=12, fontweight='bold')\n",
      "axes[1].grid(alpha=0.3, axis='y')\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/overconfidence_cost.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "\n",
      "best, worst = max(final_values.values()), min(final_values.values())\n",
      "print(f'懶人 vs 當沖達人：20年後差 {(best-worst)/1e6:.1f} 百萬元')"]),

# ── Section 4: Recency Bias + 阿媽理論 ───────────────────────────────────────

md(["## 4｜近期偏誤 & 阿媽理論：散戶在市場頂點最樂觀\n",
    "\n",
    "**近期偏誤（Recency Bias）：** 人們用最近發生的事判斷未來，而不是長期平均。\n",
    "\n",
    "具體表現：\n",
    "- 牛市第三年 → 覺得股市「永遠漲」\n",
    "- 熊市崩盤後 → 覺得股市「永遠跌」\n",
    "\n",
    "**阿媽理論（又稱鞋童理論）：**\n",
    "> 1929年，Joe Kennedy 在擦鞋時，鞋童給他股票明牌，他立刻出場——\n",
    "> 「連鞋童都在買股票，市場一定到頂了。」\n",
    "\n",
    "台灣版：**阿媽開始問你怎麼買ETF、鄰居說要拿定存去買股票 → 小心了。**\n",
    "\n",
    "學術版本：**Baker & Wurgler（2006）投資人情緒指數**——情緒高漲時，後續報酬偏低。\n",
    "\n",
    "我們用 Shiller 的數據中，散戶股票配置比例（Equity Share）作為情緒代理：\n",
    "配置比例越高 = 大家越瘋狂買股票 = 更接近市場頂點。"]),

code(["# 從 Shiller 數據：用 CAPE 高低代理散戶情緒\n",
      "# CAPE 高 = 市場樂觀、人人追捧 = 阿媽理論啟動期\n",
      "\n",
      "SHILLER_CSV = DATA_DIR / 'shiller_data.csv'\n",
      "if SHILLER_CSV.exists():\n",
      "    df = pd.read_csv(SHILLER_CSV, index_col=0, parse_dates=True)\n",
      "else:\n",
      "    import pandas_datareader.data as web\n",
      "    raw = web.DataReader('shiller', 'quandl', start='1871-01-01')\n",
      "    # fallback: download from Shiller's website\n",
      "    url = 'http://www.econ.yale.edu/~shiller/data/ie_data.xls'\n",
      "    raw = pd.read_excel(url, sheet_name='Data', skiprows=7, header=0)\n",
      "    raw = raw.dropna(subset=[raw.columns[0]])\n",
      "    df = pd.DataFrame({\n",
      "        'price': pd.to_numeric(raw.iloc[:, 2], errors='coerce'),\n",
      "        'cape':  pd.to_numeric(raw.iloc[:, 10], errors='coerce'),\n",
      "    }).dropna()\n",
      "    df.index = pd.to_datetime(raw.iloc[:len(df), 0].astype(str)\n",
      "                              .str.replace(r'\\.(\\d)$', r'.0\\1', regex=True), format='%Y.%m')\n",
      "    df.to_csv(SHILLER_CSV)\n",
      "\n",
      "# 計算後續10年實質報酬\n",
      "df = df[df['cape'].notna() & (df['cape'] > 0)].copy()\n",
      "df['real_price'] = df.get('real_price', df['price'])\n",
      "\n",
      "# 按 CAPE 分成四個情緒區間\n",
      "cape = df['cape'].dropna()\n",
      "q = [0, 0.25, 0.5, 0.75, 1.0]\n",
      "labels_q = ['低CAPE\\n(市場悲觀)', '中低CAPE', '中高CAPE', '高CAPE\\n(阿媽進場)']\n",
      "df['cape_q'] = pd.qcut(df['cape'], q=4, labels=labels_q)\n",
      "\n",
      "# 計算後續10年報酬（用 real_price 的 log return 近似）\n",
      "price_col = 'real_price' if 'real_price' in df.columns else 'price'\n",
      "df['fwd_10y'] = (df[price_col].shift(-120) / df[price_col]) ** (1/10) - 1\n",
      "df_valid = df.dropna(subset=['fwd_10y', 'cape_q'])\n",
      "\n",
      "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
      "\n",
      "# 左圖：CAPE 與後續10年報酬的關係（散點圖）\n",
      "axes[0].scatter(df_valid['cape'], df_valid['fwd_10y']*100,\n",
      "                alpha=0.25, s=8, color='#2196F3')\n",
      "\n",
      "# 四個區間的平均\n",
      "group_means = df_valid.groupby('cape_q', observed=True)['fwd_10y'].mean() * 100\n",
      "group_capes = df_valid.groupby('cape_q', observed=True)['cape'].mean()\n",
      "for lbl in labels_q:\n",
      "    if lbl in group_means.index:\n",
      "        axes[0].scatter(group_capes[lbl], group_means[lbl], s=200,\n",
      "                        color='#F44336', zorder=5)\n",
      "        axes[0].annotate(f'{lbl}\\n平均後續報酬\\n{group_means[lbl]:.1f}%/年',\n",
      "                         (group_capes[lbl], group_means[lbl]),\n",
      "                         textcoords='offset points', xytext=(10,5), fontsize=8)\n",
      "\n",
      "axes[0].axhline(0, color='black', linewidth=0.8, linestyle='--')\n",
      "axes[0].set_xlabel('當時 CAPE（市場情緒溫度計）', fontsize=11)\n",
      "axes[0].set_ylabel('後續10年年化報酬 (%)', fontsize=11)\n",
      "axes[0].set_title('CAPE 越高（大家越瘋狂買股票）\\n未來10年報酬越低', fontsize=12, fontweight='bold')\n",
      "axes[0].grid(alpha=0.3)\n",
      "\n",
      "# 右圖：各情緒區間的後續報酬分佈\n",
      "colors_box = ['#4CAF50', '#8BC34A', '#FF9800', '#F44336']\n",
      "data_box = [df_valid[df_valid['cape_q']==l]['fwd_10y'].dropna()*100 for l in labels_q]\n",
      "bp = axes[1].boxplot(data_box, labels=labels_q, patch_artist=True,\n",
      "                      medianprops={'color':'white','linewidth':2})\n",
      "for patch, color in zip(bp['boxes'], colors_box):\n",
      "    patch.set_facecolor(color)\n",
      "    patch.set_alpha(0.7)\n",
      "axes[1].axhline(0, color='black', linewidth=0.8, linestyle='--')\n",
      "axes[1].set_ylabel('後續10年年化報酬 (%)', fontsize=11)\n",
      "axes[1].set_title('阿媽進場 = 高CAPE時買入\\n後續10年報酬中位數接近0', fontsize=12, fontweight='bold')\n",
      "axes[1].grid(alpha=0.3, axis='y')\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/recency_bias_cape.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "\n",
      "print('\\n各情緒區間的後續10年年化報酬：')\n",
      "for lbl in labels_q:\n",
      "    if lbl in group_means.index:\n",
      "        print(f'  {lbl.replace(chr(10),\" \"):20s}: {group_means[lbl]:+.2f}%/年')"]),

# ── Section 5: Other Biases Quick Summary ────────────────────────────────────

md(["## 5｜其他常見散戶偏誤速覽"]),

code(["# 視覺化：七大偏誤 & 其影響方向\n",
      "biases = [\n",
      "    ('損失厭惡\\nLoss Aversion',      '不肯停損，讓虧損繼續擴大',         '展望理論 x2.25'),\n",
      "    ('處置效應\\nDisposition Effect', '賣掉漲的，留住跌的',                'Odean 1998'),\n",
      "    ('過度自信\\nOverconfidence',      '交易太頻繁，成本侵蝕報酬',          'Barber & Odean 2000'),\n",
      "    ('近期偏誤\\nRecency Bias',        '市場漲3年就覺得會永遠漲',           'Kahneman & Tversky'),\n",
      "    ('羊群效應\\nHerding',             '追高殺低，在頂點買入',               'Baker & Wurgler 2006'),\n",
      "    ('錨定效應\\nAnchoring',           '死守買入成本，不顧基本面變化',       'Kahneman & Tversky'),\n",
      "    ('心理帳戶\\nMental Accounting',   '把獲利當「賺來的」隨便花',           'Thaler 1985'),\n",
      "]\n",
      "\n",
      "fig, ax = plt.subplots(figsize=(12, 6))\n",
      "ax.set_xlim(0, 10)\n",
      "ax.set_ylim(-0.5, len(biases) - 0.5)\n",
      "ax.axis('off')\n",
      "\n",
      "colors_bias = ['#F44336','#E91E63','#FF5722','#FF9800','#FFC107','#9C27B0','#673AB7']\n",
      "\n",
      "for i, (name, effect, source) in enumerate(biases):\n",
      "    y = len(biases) - 1 - i\n",
      "    # 偏誤名稱\n",
      "    ax.add_patch(mpatches.FancyBboxPatch((0, y-0.35), 2.2, 0.7,\n",
      "                 boxstyle='round,pad=0.05', facecolor=colors_bias[i], alpha=0.85))\n",
      "    ax.text(1.1, y, name, ha='center', va='center', fontsize=9,\n",
      "            fontweight='bold', color='white')\n",
      "    # 影響\n",
      "    ax.text(2.4, y, f'→ {effect}', va='center', fontsize=9.5, color='#212121')\n",
      "    # 學術來源\n",
      "    ax.text(9.8, y, source, va='center', ha='right', fontsize=8, color='#757575',\n",
      "            style='italic')\n",
      "\n",
      "ax.text(5, len(biases)-0.1, '七大散戶認知偏誤', ha='center', fontsize=14,\n",
      "        fontweight='bold', color='#212121')\n",
      "ax.axhline(len(biases)-0.3, color='#BDBDBD', linewidth=1)\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/seven_biases.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()"]),

# ── Section 6: 這跟你有什麼關係 ──────────────────────────────────────────────

md(["## 6｜這跟你有什麼關係？\n",
    "\n",
    "### 散戶自我檢核清單\n",
    "\n",
    "在每一筆投資決策前，問自己：\n",
    "\n",
    "#### 🔴 停損相關（損失厭惡 + 處置效應）\n",
    "- [ ] 我是因為「不想承認錯誤」才沒有停損嗎？\n",
    "- [ ] 如果這支股票不是我持有的，我現在會買它嗎？\n",
    "      （如果答案是「不會」，那你只是在錨定成本，不是在投資）\n",
    "\n",
    "#### 🟡 交易頻率（過度自信）\n",
    "- [ ] 我上個月交易了幾次？成本是多少？\n",
    "- [ ] 我有記錄每次交易的「預期理由」和「實際結果」嗎？\n",
    "\n",
    "#### 🟠 市場判斷（近期偏誤 + 羊群效應）\n",
    "- [ ] 我現在覺得股市「很好」，是因為它最近確實漲了嗎？\n",
    "- [ ] 最近有沒有人（鄰居、親戚、同事）開始問我怎麼買股票？\n",
    "      （阿媽理論啟動訊號）\n",
    "\n",
    "### 阿媽理論的反向操作\n",
    "\n",
    "| 信號 | 市場可能狀態 | 建議動作 |\n",
    "|------|-------------|----------|\n",
    "| 所有人都在談股票、ETF | 可能高點 | 定期定額繼續，不要加碼 |\n",
    "| 群組開始傳「股市要崩了」 | 可能低點 | 確認基本面是否改變 |\n",
    "| 財經節目收視率創新高 | 市場頂部附近 | 小心槓桿和追高 |\n",
    "| 沒人在談股票 | 市場底部附近 | 逢低分批加碼的好時機 |\n",
    "\n",
    "### 行為金融給你的最大啟示\n",
    "\n",
    "> 你最大的敵人不是市場，而是你自己的大腦。\n",
    "\n",
    "建立**規則**，代替**感覺**：\n",
    "- 設定停損點（例如：-15% 自動檢討）\n",
    "- 定期定額（消除「現在是不是好時機」的焦慮）\n",
    "- 記錄投資日誌（讓自己的偏誤無所遁形）"]),

md(["## 📌 本章重點摘要\n",
    "| 偏誤 | 核心發現 | 對投資的影響 |\n",
    "|------|----------|-------------|\n",
    "| 損失厭惡 | 損失的痛苦是獲利喜悅的 2.25 倍 | 不肯停損，讓虧損繼續 |\n",
    "| 處置效應 | 散戶賣贏機率是賣輸的 1.5 倍 | 剛好做反了動能效應 |\n",
    "| 過度自信 | 換手率最高的散戶年報酬落後市場 5.7% | 少交易 = 多賺錢 |\n",
    "| 近期偏誤 | 市場漲三年 → 散戶最樂觀 → 往往是頂點 | 阿媽進場要小心 |\n",
    "| 解方 | 建立規則代替感覺 | 定期定額、設停損、記日誌 |\n",
    "\n",
    "> **下一章：** Shiller CAPE——用 145 年數據，看現在的股市到底貴不貴"])
]

out_path = BASE / '01_behavioral_finance.ipynb'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb(cells), f, ensure_ascii=False, indent=1)
print(f'\n✓ {out_path.name} 已生成')

# 把自身也移到 scripts/
import shutil, os
shutil.move(str(BASE / 'create_behavioral_notebook.py'),
            str(BASE / 'scripts' / 'create_behavioral_notebook.py'))

print('\n✅ 完成！最終結構：')
for p in sorted(BASE.iterdir()):
    if p.suffix == '.ipynb' or p.name in ('README.md',):
        print(f'  {p.name}')
