"""
create_research_notebooks_4.py
Generate notebooks 08-10: active stock selection empirical research
  08_ff5_quality.ipynb   — FF5 model, RMW & CMA factors
  09_capm_reality.ipynb  — CAPM vs reality, flat SML, BAB
  10_factor_zoo.ipynb    — Factor zoo & multiple testing problem
"""

import json, uuid, pathlib

def cell_id():
    return uuid.uuid4().hex[:8]

def md(source):
    return {"cell_type": "markdown", "id": cell_id(),
            "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "id": cell_id(),
            "execution_count": None, "metadata": {},
            "outputs": [], "source": source}

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.9.0"}
        },
        "cells": cells
    }

# ──────────────────────────────────────────────────────────────────────────────
# Notebook 08: FF5 Quality Factors
# ──────────────────────────────────────────────────────────────────────────────

nb08_cells = [

md(["# 08｜五因子模型：品質與保守投資的超額報酬\n",
    "\n",
    "**學術來源：** Fama & French (2015), *A Five-Factor Asset Pricing Model*, Journal of Financial Economics\n",
    "\n",
    "Fama-French 在三因子模型（市場、規模、價值）加入兩個新因子：\n",
    "- **RMW（Robust Minus Weak）**：高獲利能力公司 vs 低獲利能力公司\n",
    "- **CMA（Conservative Minus Aggressive）**：保守投資公司 vs 激進投資公司\n",
    "\n",
    "這兩個因子能解釋更多股票報酬的截面差異，也給「選好公司」提供了學術背書。"]),

md(["## 1｜三因子到五因子的演進\n",
    "\n",
    "| 因子 | 意義 | 代理變數 |\n",
    "|------|------|----------|\n",
    "| Mkt-RF | 市場風險溢酬 | 市場報酬 − 無風險利率 |\n",
    "| SMB | 規模效應（小公司溢酬） | 小市值 − 大市值 |\n",
    "| HML | 價值效應（高BM溢酬） | 高Book/Market − 低Book/Market |\n",
    "| **RMW** | **獲利能力（品質）溢酬** | **高ROE − 低ROE** |\n",
    "| **CMA** | **保守投資溢酬** | **低資本支出成長 − 高資本支出成長** |\n",
    "\n",
    "五因子模型的模型式：\n",
    "$$R_i - R_f = \\alpha + b_1(Mkt-RF) + b_2 SMB + b_3 HML + b_4 RMW + b_5 CMA + \\varepsilon$$"]),

code(["import pandas as pd\n",
      "import numpy as np\n",
      "import matplotlib\n",
      "matplotlib.rcParams['font.family'] = [\n",
      "    'Microsoft YaHei', 'SimHei', 'Heiti TC',\n",
      "    'PingFang HK', 'STHeiti', 'Arial Unicode MS', 'sans-serif'\n",
      "]\n",
      "matplotlib.rcParams['axes.unicode_minus'] = False\n",
      "import matplotlib.pyplot as plt\n",
      "import warnings\n",
      "warnings.filterwarnings('ignore')\n",
      "import pathlib, os\n",
      "\n",
      "DATA_DIR = pathlib.Path('data')\n",
      "DATA_DIR.mkdir(exist_ok=True)\n",
      "\n",
      "FF5_CSV = DATA_DIR / 'ff5_factors.csv'\n",
      "\n",
      "if FF5_CSV.exists():\n",
      "    df = pd.read_csv(FF5_CSV, index_col=0, parse_dates=True)\n",
      "    print(f'從快取載入：{len(df)} 筆月度資料')\n",
      "else:\n",
      "    import pandas_datareader.data as web\n",
      "    raw = web.DataReader('F-F_Research_Data_5_Factors_2x3', 'famafrench', start='1963-07')[0]\n",
      "    df = raw / 100\n",
      "    df.index = pd.to_datetime(df.index.to_timestamp())\n",
      "    df.to_csv(FF5_CSV)\n",
      "    print(f'下載完成：{len(df)} 筆月度資料')\n",
      "\n",
      "df.head()"]),

md(["## 2｜五個因子的年化報酬與夏普比率比較"]),

code(["factors = ['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA']\n",
      "factor_labels = {\n",
      "    'Mkt-RF': '市場溢酬\\n(Mkt-RF)',\n",
      "    'SMB':    '規模效應\\n(SMB)',\n",
      "    'HML':    '價值效應\\n(HML)',\n",
      "    'RMW':    '品質效應\\n(RMW)',\n",
      "    'CMA':    '保守投資\\n(CMA)'\n",
      "}\n",
      "\n",
      "ann_ret  = df[factors].mean() * 12\n",
      "ann_vol  = df[factors].std() * np.sqrt(12)\n",
      "sharpe   = ann_ret / ann_vol\n",
      "\n",
      "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
      "\n",
      "colors = ['#2196F3', '#9C27B0', '#FF9800', '#4CAF50', '#F44336']\n",
      "labels = [factor_labels[f] for f in factors]\n",
      "\n",
      "bars1 = axes[0].bar(labels, ann_ret * 100, color=colors, alpha=0.85, edgecolor='white')\n",
      "axes[0].axhline(0, color='black', linewidth=0.8)\n",
      "axes[0].set_title('五因子年化報酬 (%)', fontsize=14, fontweight='bold')\n",
      "axes[0].set_ylabel('年化報酬 (%)')\n",
      "for bar, val in zip(bars1, ann_ret * 100):\n",
      "    axes[0].text(bar.get_x() + bar.get_width()/2, val + 0.3 if val >= 0 else val - 0.5,\n",
      "                 f'{val:.1f}%', ha='center', va='bottom' if val >= 0 else 'top', fontsize=10)\n",
      "\n",
      "bars2 = axes[1].bar(labels, sharpe, color=colors, alpha=0.85, edgecolor='white')\n",
      "axes[1].axhline(0, color='black', linewidth=0.8)\n",
      "axes[1].set_title('五因子夏普比率', fontsize=14, fontweight='bold')\n",
      "axes[1].set_ylabel('夏普比率')\n",
      "for bar, val in zip(bars2, sharpe):\n",
      "    axes[1].text(bar.get_x() + bar.get_width()/2, val + 0.01 if val >= 0 else val - 0.02,\n",
      "                 f'{val:.2f}', ha='center', va='bottom' if val >= 0 else 'top', fontsize=10)\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/ff5_sharpe.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "print('\\n各因子統計：')\n",
      "print(pd.DataFrame({'年化報酬(%)': ann_ret*100, '年化波動(%)': ann_vol*100, '夏普比率': sharpe}).round(3))"]),

md(["## 3｜RMW（品質因子）深度分析\n",
    "\n",
    "**RMW** 代表「高獲利 minus 弱獲利」——買入高 ROE/毛利率公司、放空低獲利公司的報酬。\n",
    "\n",
    "這個因子在學術上有堅實基礎：\n",
    "- **Novy-Marx (2013)**：毛利率是最強的獲利能力代理指標\n",
    "- **Fama & French (2015)**：RMW 在五因子中有最高的統計顯著性\n",
    "- 經濟直覺：優質公司有持續競爭優勢，長期股東受益"]),

code(["# RMW 滾動10年夏普比率 → 檢驗是否跨時期穩定\n",
      "window = 120  # 10年 = 120個月\n",
      "rmw = df['RMW']\n",
      "\n",
      "rolling_mean  = rmw.rolling(window).mean() * 12\n",
      "rolling_vol   = rmw.rolling(window).std() * np.sqrt(12)\n",
      "rolling_sharpe = rolling_mean / rolling_vol\n",
      "\n",
      "fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)\n",
      "\n",
      "# 累積報酬\n",
      "cum = (1 + rmw).cumprod()\n",
      "axes[0].plot(cum.index, cum, color='#4CAF50', linewidth=1.5)\n",
      "axes[0].fill_between(cum.index, 1, cum, where=(cum >= 1), alpha=0.2, color='#4CAF50')\n",
      "axes[0].fill_between(cum.index, 1, cum, where=(cum < 1),  alpha=0.2, color='#F44336')\n",
      "axes[0].axhline(1, color='black', linewidth=0.8, linestyle='--')\n",
      "axes[0].set_title('RMW（品質因子）累積報酬（1963–至今）', fontsize=13, fontweight='bold')\n",
      "axes[0].set_ylabel('累積倍數')\n",
      "axes[0].set_yscale('log')\n",
      "\n",
      "# 滾動夏普\n",
      "axes[1].plot(rolling_sharpe.index, rolling_sharpe, color='#2196F3', linewidth=1.5)\n",
      "axes[1].axhline(0, color='black', linewidth=0.8)\n",
      "axes[1].axhline(rolling_sharpe.mean(), color='orange', linewidth=1.2, linestyle='--', label=f'平均={rolling_sharpe.mean():.2f}')\n",
      "axes[1].fill_between(rolling_sharpe.index, 0, rolling_sharpe,\n",
      "                     where=(rolling_sharpe >= 0), alpha=0.2, color='#2196F3')\n",
      "axes[1].fill_between(rolling_sharpe.index, 0, rolling_sharpe,\n",
      "                     where=(rolling_sharpe < 0),  alpha=0.2, color='#F44336')\n",
      "axes[1].set_title('RMW 滾動10年夏普比率', fontsize=13, fontweight='bold')\n",
      "axes[1].set_ylabel('夏普比率')\n",
      "axes[1].legend()\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/rmw_analysis.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "\n",
      "pct_positive = (rolling_sharpe.dropna() > 0).mean()\n",
      "print(f'RMW 夏普比率為正的月份占比：{pct_positive:.1%}')\n",
      "print(f'RMW 整體夏普比率：{(rmw.mean()*12)/(rmw.std()*np.sqrt(12)):.3f}')"]),

md(["## 4｜CMA（保守投資因子）與品質價值組合\n",
    "\n",
    "**CMA** 捕捉「少投資」的公司溢酬：\n",
    "- **理論**：Modigliani-Miller 的投資規則——NPV>0 才投資，否則應還給股東\n",
    "- **實證**：大量資本支出往往預示未來報酬下降（過度自信的管理層）\n",
    "- **Titman et al. (2004)**：高 capex 增長公司未來三年股票報酬顯著偏低\n",
    "\n",
    "**RMW + HML（品質+價值）** 組合是許多價值投資者的最愛。"]),

code(["# 品質+價值組合 vs 單因子\n",
      "combo = (df['RMW'] + df['HML']) / 2\n",
      "\n",
      "series_dict = {\n",
      "    'Mkt-RF（市場）': df['Mkt-RF'],\n",
      "    'HML（價值）':    df['HML'],\n",
      "    'RMW（品質）':    df['RMW'],\n",
      "    '品質+價值 組合': combo,\n",
      "}\n",
      "\n",
      "fig, ax = plt.subplots(figsize=(13, 6))\n",
      "style_map = {'Mkt-RF（市場）': ('#9E9E9E', 0.7, 1.2),\n",
      "             'HML（價值）':    ('#FF9800', 0.85, 1.5),\n",
      "             'RMW（品質）':    ('#4CAF50', 0.85, 1.5),\n",
      "             '品質+價值 組合': ('#E91E63', 1.0, 2.5)}\n",
      "\n",
      "for name, s in series_dict.items():\n",
      "    cum = (1 + s).cumprod()\n",
      "    color, alpha, lw = style_map[name]\n",
      "    ax.plot(cum.index, cum, label=name, color=color, alpha=alpha, linewidth=lw)\n",
      "\n",
      "ax.set_yscale('log')\n",
      "ax.set_title('品質+價值組合 vs 單因子累積報酬（對數尺度）', fontsize=14, fontweight='bold')\n",
      "ax.set_ylabel('累積倍數（對數）')\n",
      "ax.legend(fontsize=11)\n",
      "ax.grid(alpha=0.3)\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/quality_value_combo.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "\n",
      "for name, s in series_dict.items():\n",
      "    ann_r = s.mean() * 12\n",
      "    ann_v = s.std() * np.sqrt(12)\n",
      "    sh = ann_r / ann_v\n",
      "    print(f'{name:15s}: 年化報酬={ann_r*100:.2f}%，夏普={sh:.3f}')"]),

md(["## 5｜這跟你有什麼關係？\n",
    "\n",
    "### 五因子告訴你的三件事\n",
    "\n",
    "**① 選「賺錢的公司」有統計基礎**\n",
    "\n",
    "RMW 因子的存在告訴你：長期持有高 ROE、高毛利率公司，確實有超額報酬。\n",
    "這不是股市玄學，而是 60 年美股數據的實證結果。\n",
    "\n",
    "**② 「不亂花錢的公司」也有超額報酬**\n",
    "\n",
    "CMA 因子：管理層把錢存起來或還給股東（配息/回購），比一直擴張的公司報酬更好。\n",
    "檢驗方式：看「自由現金流/資本支出比率」。FCF > capex 的公司才是保守投資者。\n",
    "\n",
    "**③ 品質+價值 > 單一因子**\n",
    "\n",
    "RMW（品質）和 HML（低估值）組合的夏普比率，比任何單一因子都高。\n",
    "實務上的篩選條件：**ROE > 15% 且 P/B < 3 且 FCF > 0**\n",
    "\n",
    "### 台灣投資人的操作方向\n",
    "\n",
    "| 方法 | 說明 |\n",
    "|------|------|\n",
    "| **買因子 ETF** | 美國有 QUAL（品質）、MOAT（護城河）等 ETF 直接捕捉 RMW |\n",
    "| **個股篩選** | 用 CMoney/Goodinfo 篩 ROE>15%、負債比<40%、連續3年正FCF |\n",
    "| **避開陷阱** | 大幅增資、頻繁購廠的公司→ 小心 CMA 反轉 |"]),

]

# ──────────────────────────────────────────────────────────────────────────────
# Notebook 09: CAPM Reality & BAB
# ──────────────────────────────────────────────────────────────────────────────

nb09_cells = [

md(["# 09｜CAPM 的現實：平坦的 SML 與低波動溢酬\n",
    "\n",
    "**學術來源：**\n",
    "- Black, Jensen & Scholes (1972)：SML 比 CAPM 預測更平坦\n",
    "- Frazzini & Pedersen (2014), *Betting Against Beta*, Journal of Financial Economics\n",
    "\n",
    "CAPM 預測：高 β 股票應有更高報酬（承擔更多市場風險）。\n",
    "\n",
    "**現實是**：高 β 股票的報酬並不像 CAPM 預測那樣高；低 β 股票的報酬卻超出預期。\n",
    "\n",
    "這個現象稱為 **「低波動異象（Low-Volatility Anomaly）」**，\n",
    "也催生了一個可交易策略：**Betting Against Beta（BAB）**。"]),

md(["## 1｜CAPM 複習：預測與現實的落差\n",
    "\n",
    "**CAPM 公式：**\n",
    "$$E[R_i] - R_f = \\beta_i \\cdot (E[R_m] - R_f)$$\n",
    "\n",
    "所以在「安全市場線（SML）」上：\n",
    "- β=0：報酬 = 無風險利率\n",
    "- β=1：報酬 = 市場報酬\n",
    "- β=2：報酬 = 市場溢酬的兩倍\n",
    "\n",
    "**實證發現：** SML 斜率遠低於 CAPM 預測，大約是預測值的 40–60%。\n",
    "換言之，β 每增加 1，實際額外報酬遠小於理論值。"]),

code(["import pandas as pd\n",
      "import numpy as np\n",
      "import matplotlib\n",
      "matplotlib.rcParams['font.family'] = [\n",
      "    'Microsoft YaHei', 'SimHei', 'Heiti TC',\n",
      "    'PingFang HK', 'STHeiti', 'Arial Unicode MS', 'sans-serif'\n",
      "]\n",
      "matplotlib.rcParams['axes.unicode_minus'] = False\n",
      "import matplotlib.pyplot as plt\n",
      "from scipy import stats\n",
      "import warnings, pathlib\n",
      "warnings.filterwarnings('ignore')\n",
      "\n",
      "DATA_DIR = pathlib.Path('data')\n",
      "DATA_DIR.mkdir(exist_ok=True)\n",
      "\n",
      "FF25_CSV = DATA_DIR / 'ff25_portfolios.csv'\n",
      "FF3_CSV  = DATA_DIR / 'ff3_factors.csv'\n",
      "\n",
      "# 載入 FF3\n",
      "if FF3_CSV.exists():\n",
      "    ff3 = pd.read_csv(FF3_CSV, index_col=0, parse_dates=True)\n",
      "    print(f'FF3 從快取載入：{len(ff3)} 筆')\n",
      "else:\n",
      "    import pandas_datareader.data as web\n",
      "    raw3 = web.DataReader('F-F_Research_Data_Factors', 'famafrench', start='1963-07')[0]\n",
      "    ff3 = raw3 / 100\n",
      "    ff3.index = pd.to_datetime(ff3.index.to_timestamp())\n",
      "    ff3.to_csv(FF3_CSV)\n",
      "    print(f'FF3 下載完成：{len(ff3)} 筆')\n",
      "\n",
      "# 載入 FF25 (25 Portfolios sorted by Size x BM)\n",
      "if FF25_CSV.exists():\n",
      "    ff25 = pd.read_csv(FF25_CSV, index_col=0, parse_dates=True)\n",
      "    print(f'FF25 從快取載入：{ff25.shape}')\n",
      "else:\n",
      "    import pandas_datareader.data as web\n",
      "    raw25 = web.DataReader('25_Portfolios_5x5', 'famafrench', start='1963-07')[0]\n",
      "    ff25 = raw25 / 100\n",
      "    ff25.index = pd.to_datetime(ff25.index.to_timestamp())\n",
      "    ff25.to_csv(FF25_CSV)\n",
      "    print(f'FF25 下載完成：{ff25.shape}')\n",
      "\n",
      "# 對齊時間\n",
      "common = ff3.index.intersection(ff25.index)\n",
      "ff3  = ff3.loc[common]\n",
      "ff25 = ff25.loc[common]\n",
      "print(f'\\n對齊後：{len(common)} 個月（{common[0].year}–{common[-1].year}）')"]),

md(["## 2｜計算 25 個投資組合的 β 與平均超額報酬"]),

code(["mkt_rf = ff3['Mkt-RF'].values\n",
      "rf     = ff3['RF'].values\n",
      "\n",
      "results = []\n",
      "for col in ff25.columns:\n",
      "    port_ret = ff25[col].values\n",
      "    excess   = port_ret - rf\n",
      "    slope, intercept, r, p, se = stats.linregress(mkt_rf, excess)\n",
      "    ann_excess = excess.mean() * 12\n",
      "    results.append({\n",
      "        'portfolio': col,\n",
      "        'beta':      slope,\n",
      "        'alpha':     intercept * 12,\n",
      "        'ann_excess': ann_excess,\n",
      "        'r2':        r**2\n",
      "    })\n",
      "\n",
      "res_df = pd.DataFrame(results)\n",
      "print(res_df.sort_values('beta')[['portfolio','beta','ann_excess','alpha','r2']].to_string(index=False))"]),

md(["## 3｜安全市場線：預測 vs 現實"]),

code(["mkt_premium = ff3['Mkt-RF'].mean() * 12  # CAPM 預測斜率\n",
      "rf_ann      = ff3['RF'].mean() * 12\n",
      "\n",
      "beta_range = np.linspace(res_df['beta'].min() - 0.1, res_df['beta'].max() + 0.1, 100)\n",
      "capm_pred  = mkt_premium * beta_range\n",
      "\n",
      "# 實際 SML（OLS 擬合）\n",
      "act_slope, act_intercept, *_ = stats.linregress(res_df['beta'], res_df['ann_excess'])\n",
      "actual_line = act_intercept + act_slope * beta_range\n",
      "\n",
      "fig, ax = plt.subplots(figsize=(10, 7))\n",
      "\n",
      "ax.plot(beta_range, capm_pred,  '--', color='#F44336', linewidth=2,\n",
      "        label=f'CAPM 預測 SML（斜率={mkt_premium*100:.1f}%）')\n",
      "ax.plot(beta_range, actual_line, '-', color='#2196F3', linewidth=2,\n",
      "        label=f'實際 SML（斜率={act_slope*100:.1f}%）')\n",
      "ax.scatter(res_df['beta'], res_df['ann_excess'],\n",
      "           c='#4CAF50', s=60, zorder=5, label='FF25 投資組合')\n",
      "ax.axhline(0, color='black', linewidth=0.8, linestyle=':')\n",
      "\n",
      "coverage = act_slope / mkt_premium\n",
      "ax.set_title(f'安全市場線：預測 vs 現實\\n（實際斜率 ≈ CAPM 預測的 {coverage:.0%}）',\n",
      "             fontsize=13, fontweight='bold')\n",
      "ax.set_xlabel('Beta（系統性風險）', fontsize=12)\n",
      "ax.set_ylabel('年化超額報酬 (%)', fontsize=12)\n",
      "ax.legend(fontsize=11)\n",
      "ax.grid(alpha=0.3)\n",
      "\n",
      "# 格式化 y 軸為百分比\n",
      "import matplotlib.ticker as mticker\n",
      "ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x*100:.1f}%'))\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/sml_reality.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "print(f'CAPM 預測市場溢酬：{mkt_premium*100:.2f}%/年')\n",
      "print(f'實際 SML 斜率：    {act_slope*100:.2f}%/年')\n",
      "print(f'實際斜率 = CAPM 預測的 {coverage:.1%}')"]),

md(["## 4｜BAB 代理策略：低 β 組合 vs 高 β 組合\n",
    "\n",
    "**Frazzini & Pedersen（2014）** 的 BAB 因子：\n",
    "- 買入低 β 股票（去槓桿化到 β=1）\n",
    "- 放空高 β 股票（去槓桿化到 β=1）\n",
    "\n",
    "我們用 FF25 的最低 β 五個組合 vs 最高 β 五個組合做簡單代理。"]),

code(["# 按 beta 排序，取最低/最高五個\n",
      "res_sorted = res_df.sort_values('beta')\n",
      "low_beta_ports  = res_sorted.head(5)['portfolio'].tolist()\n",
      "high_beta_ports = res_sorted.tail(5)['portfolio'].tolist()\n",
      "\n",
      "low_ret  = ff25[low_beta_ports].mean(axis=1)\n",
      "high_ret = ff25[high_beta_ports].mean(axis=1)\n",
      "bab_proxy = low_ret - high_ret\n",
      "\n",
      "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
      "\n",
      "# 累積報酬\n",
      "for name, s, color in [('低 β 組合', low_ret, '#4CAF50'),\n",
      "                        ('高 β 組合', high_ret, '#F44336'),\n",
      "                        ('市場', ff3['Mkt-RF']+ff3['RF'], '#9E9E9E')]:\n",
      "    cum = (1 + s).cumprod()\n",
      "    axes[0].plot(cum.index, cum, label=name, color=color,\n",
      "                 linewidth=2 if name != '市場' else 1.2,\n",
      "                 alpha=1.0 if name != '市場' else 0.6)\n",
      "\n",
      "axes[0].set_yscale('log')\n",
      "axes[0].set_title('低 β vs 高 β 組合累積報酬', fontsize=13, fontweight='bold')\n",
      "axes[0].set_ylabel('累積倍數（對數）')\n",
      "axes[0].legend()\n",
      "axes[0].grid(alpha=0.3)\n",
      "\n",
      "# BAB 代理因子\n",
      "cum_bab = (1 + bab_proxy).cumprod()\n",
      "axes[1].plot(cum_bab.index, cum_bab, color='#9C27B0', linewidth=1.5)\n",
      "axes[1].fill_between(cum_bab.index, 1, cum_bab,\n",
      "                     where=(cum_bab >= 1), alpha=0.2, color='#4CAF50')\n",
      "axes[1].fill_between(cum_bab.index, 1, cum_bab,\n",
      "                     where=(cum_bab < 1),  alpha=0.2, color='#F44336')\n",
      "axes[1].axhline(1, color='black', linewidth=0.8, linestyle='--')\n",
      "axes[1].set_title('BAB 代理因子（低β − 高β）累積報酬', fontsize=13, fontweight='bold')\n",
      "axes[1].set_ylabel('累積倍數')\n",
      "axes[1].grid(alpha=0.3)\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/bab_proxy.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()\n",
      "\n",
      "for name, s in [('低β組合', low_ret), ('高β組合', high_ret), ('BAB代理', bab_proxy)]:\n",
      "    ann_r = s.mean() * 12\n",
      "    ann_v = s.std() * np.sqrt(12)\n",
      "    print(f'{name}: 年化報酬={ann_r*100:.2f}%，夏普={ann_r/ann_v:.3f}')"]),

md(["## 5｜這跟你有什麼關係？\n",
    "\n",
    "### 三個反直覺但重要的結論\n",
    "\n",
    "**① 「高風險 = 高報酬」在股票 β 上並不成立**\n",
    "\n",
    "CAPM 是財務學的基石，但它的核心預測——高 β 股票帶來高報酬——被 60 年數據反駁。\n",
    "實際上，SML 的斜率約是 CAPM 預測的 40–60%。\n",
    "\n",
    "**② 為什麼低 β 股反而有好報酬？**\n",
    "\n",
    "Frazzini & Pedersen 的解釋：\n",
    "- 有槓桿限制的機構投資人（退休基金等）**只能買股票，不能用槓桿**\n",
    "- 他們選擇高 β 股票來「放大」曝險 → 把高 β 股推得過貴\n",
    "- 低 β 股被忽視 → 相對低估\n",
    "\n",
    "**③ 實務應用：低波動 ETF 的學術根基**\n",
    "\n",
    "| 工具 | 說明 |\n",
    "|------|------|\n",
    "| **USMV**（iShares MSCI Min Vol USA） | 最大化分散同時最小化波動 |\n",
    "| **SPLV**（Invesco S&P 500 Low Vol） | 直接選 S&P500 中最低波動的 100 檔 |\n",
    "| **個股思維** | 選 β < 0.8 的優質股，而非追逐高 β 飆股 |\n",
    "\n",
    "注意：低波動策略在牛市中通常落後大盤，但長期夏普比率更高——你願意接受嗎？"]),

]

# ──────────────────────────────────────────────────────────────────────────────
# Notebook 10: Factor Zoo
# ──────────────────────────────────────────────────────────────────────────────

nb10_cells = [

md(["# 10｜因子動物園：當學術論文太多，你該怎麼辦？\n",
    "\n",
    "**學術來源：**\n",
    "- Harvey, Liu & Zhu (2016), *… and the Cross-Section of Expected Returns*, Review of Financial Studies\n",
    "- Cochrane (2011), *Discount Rates*（AFA 主席演講）\n",
    "\n",
    "截至 2023 年，學術論文已發表超過 **400 個** 聲稱能預測股票報酬的「因子」。\n",
    "這個現象被 Cochrane（2011）戲稱為 **因子動物園（Factor Zoo）**。\n",
    "\n",
    "問題核心：**這些因子是真實的嗎？還是純粹的資料探勘（Data Mining）？**"]),

md(["## 1｜多重檢定問題（Multiple Testing Problem）\n",
    "\n",
    "**傳統統計顯著性：** t > 1.96（α = 5%）\n",
    "\n",
    "如果你同時測試 100 個策略：\n",
    "- 即使所有策略都沒有真實效果（全是雜訊）\n",
    "- 平均仍有 **5 個** 會偶然達到 t > 1.96\n",
    "\n",
    "Harvey et al.（2016）建議：在考慮多重檢定後，新因子的閾值應提高到 **t > 3.0**。\n",
    "\n",
    "他們的資料庫中，歷史上發表的因子有 **85%** 的 t 值在 1.96–3.0 之間，\n",
    "這些因子可能只是統計噪音，而非真實的市場異象。"]),

code(["import pandas as pd\n",
      "import numpy as np\n",
      "import matplotlib\n",
      "matplotlib.rcParams['font.family'] = [\n",
      "    'Microsoft YaHei', 'SimHei', 'Heiti TC',\n",
      "    'PingFang HK', 'STHeiti', 'Arial Unicode MS', 'sans-serif'\n",
      "]\n",
      "matplotlib.rcParams['axes.unicode_minus'] = False\n",
      "import matplotlib.pyplot as plt\n",
      "from scipy import stats\n",
      "import warnings, pathlib\n",
      "warnings.filterwarnings('ignore')\n",
      "\n",
      "DATA_DIR = pathlib.Path('data')\n",
      "rng = np.random.default_rng(42)\n",
      "\n",
      "# 模擬：在完全隨機數據中，多重檢定產生多少假陽性\n",
      "N_FACTORS  = 1000  # 測試因子數\n",
      "N_MONTHS   = 120   # 每個因子測試 120 個月\n",
      "\n",
      "t_stats = []\n",
      "for _ in range(N_FACTORS):\n",
      "    # 純隨機因子，真實超額報酬 = 0\n",
      "    returns = rng.normal(0, 1, N_MONTHS)\n",
      "    t_stat  = returns.mean() / (returns.std() / np.sqrt(N_MONTHS))\n",
      "    t_stats.append(abs(t_stat))\n",
      "\n",
      "t_stats = np.array(t_stats)\n",
      "\n",
      "fp_196 = (t_stats > 1.96).sum()\n",
      "fp_300 = (t_stats > 3.00).sum()\n",
      "print(f'在 {N_FACTORS} 個純隨機因子中：')\n",
      "print(f'  t > 1.96（傳統 5% 顯著）：{fp_196} 個 ({fp_196/N_FACTORS:.1%})')\n",
      "print(f'  t > 3.00（Harvey建議）   ：{fp_300} 個 ({fp_300/N_FACTORS:.1%})')"]),

md(["## 2｜視覺化：t 統計量的分布與假陽性區域"]),

code(["fig, ax = plt.subplots(figsize=(11, 6))\n",
      "\n",
      "ax.hist(t_stats, bins=50, color='#2196F3', alpha=0.7, edgecolor='white', label='隨機因子 t 統計量')\n",
      "\n",
      "# 理論卡方分配（null hypothesis 下的 |t| 分配近似）\n",
      "x = np.linspace(0, t_stats.max() + 0.5, 200)\n",
      "# 使用摺疊常態（|t| 的近似）\n",
      "folded = stats.norm.pdf(x) * 2 * N_FACTORS * (t_stats.max() / 10)\n",
      "\n",
      "ax.axvline(1.96, color='#FF9800', linewidth=2, linestyle='--', label=f't=1.96（傳統 5%）: {fp_196} 個假陽性')\n",
      "ax.axvline(3.00, color='#F44336', linewidth=2, linestyle='--', label=f't=3.00（Harvey 建議）: {fp_300} 個假陽性')\n",
      "\n",
      "# 標注假陽性區域\n",
      "ymax = ax.get_ylim()[1] if ax.get_ylim()[1] > 0 else 50\n",
      "hist_vals, hist_edges = np.histogram(t_stats, bins=50)\n",
      "ymax = hist_vals.max()\n",
      "\n",
      "ax.fill_betweenx([0, ymax * 1.05], 1.96, 3.00, alpha=0.1, color='#FF9800', label='傳統顯著但 Harvey 不認可的區域')\n",
      "ax.fill_betweenx([0, ymax * 1.05], 3.00, t_stats.max() + 0.5, alpha=0.1, color='#F44336', label='Harvey 認可的顯著區域')\n",
      "\n",
      "ax.set_xlabel('|t 統計量|', fontsize=12)\n",
      "ax.set_ylabel('因子數量', fontsize=12)\n",
      "ax.set_title(f'多重檢定模擬：{N_FACTORS} 個純隨機因子的 t 統計量分布\\n（真實超額報酬 = 0，但傳統標準仍有 {fp_196/N_FACTORS:.1%} 假陽性）',\n",
      "             fontsize=12, fontweight='bold')\n",
      "ax.legend(fontsize=10, loc='upper right')\n",
      "ax.grid(alpha=0.3)\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/factor_zoo_tstat.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()"]),

md(["## 3｜真實因子的 t 統計量 vs Harvey 閾值"]),

code(["# 載入所有已快取的因子\n",
      "factor_files = {\n",
      "    'FF3 (Mkt-RF, SMB, HML)': DATA_DIR / 'ff3_factors.csv',\n",
      "    'FF5 (RMW, CMA)':         DATA_DIR / 'ff5_factors.csv',\n",
      "    'Momentum':                DATA_DIR / 'ff_momentum.csv',\n",
      "}\n",
      "\n",
      "all_factors = {}\n",
      "for desc, fpath in factor_files.items():\n",
      "    if fpath.exists():\n",
      "        tmp = pd.read_csv(fpath, index_col=0, parse_dates=True)\n",
      "        for col in tmp.columns:\n",
      "            if col != 'RF':\n",
      "                all_factors[col] = tmp[col]\n",
      "\n",
      "factor_df = pd.DataFrame(all_factors).dropna()\n",
      "\n",
      "t_real = {}\n",
      "for col in factor_df.columns:\n",
      "    s = factor_df[col]\n",
      "    t_val = s.mean() / (s.std() / np.sqrt(len(s)))\n",
      "    t_real[col] = abs(t_val)\n",
      "\n",
      "t_series = pd.Series(t_real).sort_values(ascending=True)\n",
      "\n",
      "fig, ax = plt.subplots(figsize=(9, 5))\n",
      "colors_bar = ['#4CAF50' if v > 3.0 else '#FF9800' if v > 1.96 else '#F44336'\n",
      "              for v in t_series]\n",
      "bars = ax.barh(t_series.index, t_series.values, color=colors_bar, alpha=0.85)\n",
      "ax.axvline(1.96, color='#FF9800', linewidth=1.5, linestyle='--', label='t=1.96（傳統）')\n",
      "ax.axvline(3.00, color='#4CAF50', linewidth=1.5, linestyle='--', label='t=3.00（Harvey）')\n",
      "for bar, val in zip(bars, t_series.values):\n",
      "    ax.text(val + 0.1, bar.get_y() + bar.get_height()/2,\n",
      "            f'{val:.2f}', va='center', fontsize=10)\n",
      "ax.set_xlabel('|t 統計量|（全樣本期間）', fontsize=11)\n",
      "ax.set_title('已知學術因子的 t 統計量\\n（綠色 = Harvey 認可，橘色 = 傳統顯著但可疑）',\n",
      "             fontsize=12, fontweight='bold')\n",
      "ax.legend(fontsize=10)\n",
      "ax.grid(alpha=0.3, axis='x')\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/factor_tstats.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()"]),

md(["## 4｜因子報酬的時間不穩定性：滾動夏普比率"]),

code(["window = 120  # 10 年\n",
      "fig, axes = plt.subplots(len(factor_df.columns), 1,\n",
      "                          figsize=(12, 3 * len(factor_df.columns)),\n",
      "                          sharex=True)\n",
      "if len(factor_df.columns) == 1:\n",
      "    axes = [axes]\n",
      "\n",
      "for ax, col in zip(axes, factor_df.columns):\n",
      "    s = factor_df[col]\n",
      "    roll_sh = (s.rolling(window).mean() * 12) / (s.rolling(window).std() * np.sqrt(12))\n",
      "    ax.plot(roll_sh.index, roll_sh, linewidth=1.2, color='#2196F3')\n",
      "    ax.axhline(0, color='black', linewidth=0.8)\n",
      "    ax.axhline(roll_sh.mean(), color='orange', linewidth=1.0,\n",
      "               linestyle='--', label=f'平均={roll_sh.mean():.2f}')\n",
      "    ax.fill_between(roll_sh.index, 0, roll_sh,\n",
      "                    where=(roll_sh >= 0), alpha=0.15, color='#4CAF50')\n",
      "    ax.fill_between(roll_sh.index, 0, roll_sh,\n",
      "                    where=(roll_sh < 0),  alpha=0.15, color='#F44336')\n",
      "    pct_neg = (roll_sh.dropna() < 0).mean()\n",
      "    ax.set_title(f'{col} — 滾動10年夏普比率（{pct_neg:.0%}時段為負）',\n",
      "                 fontsize=11, fontweight='bold')\n",
      "    ax.legend(fontsize=9)\n",
      "    ax.grid(alpha=0.2)\n",
      "\n",
      "plt.suptitle('所有因子的時間不穩定性（滾動10年夏普）', fontsize=13, fontweight='bold', y=1.01)\n",
      "plt.tight_layout()\n",
      "plt.savefig('data/factor_rolling_sharpe.png', dpi=150, bbox_inches='tight')\n",
      "plt.show()"]),

md(["## 5｜這跟你有什麼關係？\n",
    "\n",
    "### 評估「投資策略」的防騙檢核清單\n",
    "\n",
    "當有人告訴你某個因子/策略「學術研究證實有效」，請用以下問題過濾：\n",
    "\n",
    "#### 統計層面\n",
    "- [ ] **t 統計量 > 3.0 嗎？** 只達到 1.96 的策略有很高機率是資料探勘\n",
    "- [ ] **樣本外（out-of-sample）驗證了嗎？** 在其他國家、其他時期仍有效嗎？\n",
    "- [ ] **有多少個人測試了幾個策略？** 10 個人各測 100 個，一定有人找到「顯著」策略\n",
    "\n",
    "#### 經濟層面\n",
    "- [ ] **有合理的經濟解釋嗎？** 純粹的數字遊戲沒有持久性\n",
    "- [ ] **考慮交易成本了嗎？** 許多高換手率因子在扣費後消失\n",
    "- [ ] **公布後報酬是否縮水？** McLean & Pontiff（2016）：因子被發表後，平均報酬下降 32%\n",
    "\n",
    "#### 時間層面\n",
    "- [ ] **過去10年每個10年滾動期都有效嗎？** 還是只靠某個特殊時期撐起來的？\n",
    "- [ ] **最大回撤期有多長？** 能撐過5年以上的連續虧損嗎？\n",
    "\n",
    "### 倖存偏差（Survivorship Bias）\n",
    "\n",
    "你在網路上看到的「有效策略」，都是存活下來的——那些失敗的策略沉默地消失了。\n",
    "\n",
    "這不代表所有策略無效，而是：**做好統計衛生，要求更高的證明標準**。\n",
    "\n",
    "### 底線建議\n",
    "\n",
    "| 策略類型 | 建議 |\n",
    "|----------|------|\n",
    "| 有60年數據支撐、t>3、多國驗證 | Mkt、SMB、HML、RMW、Mom — 可考慮 |\n",
    "| 學術論文支撐但 t 在 1.96–3.0 | 存疑，等待更多驗證 |\n",
    "| 回測表現很好但沒有經濟解釋 | 大概率是資料探勘，避開 |\n",
    "| 只有近5年數據 | 樣本太小，無法判斷 |"]),

]


# ──────────────────────────────────────────────────────────────────────────────
# Write notebooks
# ──────────────────────────────────────────────────────────────────────────────

base = pathlib.Path('/Users/tsaichengyu/Documents/Projects/Academic/學術研究_教材')

notebooks = [
    ('08_ff5_quality.ipynb',   nb08_cells),
    ('09_capm_reality.ipynb',  nb09_cells),
    ('10_factor_zoo.ipynb',    nb10_cells),
]

for fname, cells in notebooks:
    fpath = base / fname
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(nb(cells), f, ensure_ascii=False, indent=1)
    print(f'Written: {fpath}')

print('\n全部完成！')
